baseurl = "/"
defaultContentLanguage = "de"
title = "Hotel & Restaurant Peterle"

enableRobotsTXT = true
disableKinds = ["RSS", "taxonomy", "taxonomyTerm"]

[languages]
  [languages.de]
    locale = "de_DE"
    weight = 1

  [languages.en]
    locale = "en_GB"
    weight = 2

[params]
  facebookURL = "https://www.facebook.com/pages/Hotel-Peterle/132155553500218"
